version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.41
    environment:
      - COLLECTOR_ZIPKIN_HTTP_HTTP_PORT=9411
    ports:
      - "5775:5775"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger HTTP Collector
      - "14250:14250"  # Jaeger gRPC
      - "9411:9411"    # Zipkin
