{
 "title": "Express.js Node Application Application Performance Dashboard",
 "tags": [
  "app-metrics",
  "performance",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (Total)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "my_app_process_cpu_seconds_total",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "HTTP Response Time Distribution(Sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "http_response_time_seconds_bucket/10000",
     "legendFormat": "{{route}} - Response Time"
    }
   ]
  },
  {
   "title": "Memory Usage (Resident)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "my_app_process_resident_memory_bytes",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "targets": [
    {
     "expr": "my_app_nodejs_gc_duration_seconds_sum{kind='major'}",
     "legendFormat": "Major GC"
    }
   ]
  },
  {
   "title": "Active Resources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "my_app_nodejs_active_resources_total",
     "legendFormat": "Active Resources"
    }
   ]
  },
  {
   "title": "HTTP Request Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{method}} {{route}}" }
   ]
  },
  {
   "title": "Heap Size Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "my_app_nodejs_heap_size_used_bytes",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "my_app_nodejs_heap_size_total_bytes",
     "legendFormat": "Total Heap"
    }
   ]
  },
  {
   "title": "Event Loop Lag (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "my_app_nodejs_eventloop_lag_seconds",
     "legendFormat": "Event Loop Lag"
    }
   ]
  }
 ]
}