global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app-observability'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
      - targets: ['host.docker.internal:30001']
